version: '3.1'
services:
  postgres:
    image: postgres
    restart: always
    env_file:
      - configs.env
    networks:
      - gcmedia-net
    ports:
      - "5432:5432"
    volumes:
      - ~/data/postgres:/var/lib/postgresql/data
    labels:
      - "traefik.backend=database"
      - "traefik.docker.network=gcmedia-net"
      - "traefik.enable=true"
      - "traefik.protocol=http"
      - "traefik.frontend.rule=Host:database.thegc.website"
      - "traefik.port=5432"
networks:
  gcmedia-net:
