version: '3.1'
services:
  traefik:
    image: traefik:1.5.4
    restart: always
    ports:
      - 80:80
      - 443:443
    networks:
      - gcmedia-net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/traefik.toml
      - ./acme.json:/acme.json
    container_name: traefik
  database:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file:
      - configs.env
    networks:
      - gcmedia-net
    expose:
      - "3306"
    volumes:
      - ~/data/mysql:/var/lib/mysql
      - ./scripts.sql:/docker-entrypoint-initdb.d/scripts.sql
    labels:
      - "traefik.backend=database"
      - "traefik.docker.network=gcmedia-net"
      - "traefik.enable=true"
      - "traefik.protocol=http"
      - "traefik.frontend.rule=Host:database.thegc.cf"
      - "traefik.port=3306"
  adminer:
    image: adminer
    restart: always
    networks:
      - gcmedia-net
    container_name: adminer
    expose:
      - "8080"
    labels:
      - "traefik.backend=adminer"
      - "traefik.docker.network=gcmedia-net"
      - "traefik.enable=true"
      - "traefik.protocol=http"
      - "traefik.frontend.rule=Host:adminer.thegc.cf"
      - "traefik.port=8080"
  portainer:
    image: portainer/portainer
    restart: always
    expose:
      - "9000"
    command: -H unix:///var/run/docker.sock
    networks:
      - gcmedia-net
    container_name: portainer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer-volume:/data
    labels:
      - "traefik.frontend.rule=Host:portainer.thegc.cf"
      - "traefik.enable=true"
      - "traefik.docker.network=gcmedia-net"
      - "traefik.port=9000"
      - "traefik.backend=portainer"
networks:
  gcmedia-net:
    external: true
volumes:
  portainer-volume:
    external: true
  mysql:
